use databaseingexis;
--======================================--
-- CREATE FUNCTION  correoExistente(correo varchar(50)) returns varchar(5)
-- BEGIN
--     DECLARE respuesta int;
--     select log_usuarios.id_usuario into respuesta from log_usuarios where log_usuarios.correo = correo;
--     if respuesta != 1 then
--         return 'true';
--     else
--         return 'false';
--     end if;
-- END
--======================================--
-- CREATE FUNCTION verificaContraseña(correo varchar(50), contraseña varchar(20)) returns varchar(5)
-- begin
--     declare respuesta bit;
--     select if(log_usuarios.contra, 1, 0) into respuesta from log_usuarios where log_usuarios.correo = correo and log_usuarios.contra = contraseña;
--     if respuesta = 1 then
--         return 'true';
--     else
--         return 'false';
--     end if;
-- end
--======================================--
-- create FUNCTION id_by_correo(correo varchar(50)) returns int
-- begin
--     declare salida int;
--     select log_usuarios.id_usuario into salida from log_usuarios where log_usuarios.correo = correo;
--     return salida;
-- end
--======================================--