--CREATE database databaseingexis;
--======================================--
use databaseingexis;
--======================================--
-- create table Log_usuarios(
--     id_usuario      int             primary key     not null    AUTO_INCREMENT,
--     correo          varchar(50)     unique,
--     contra          varchar(20),
--     img_log         VARCHAR(100)
-- );
--======================================--
-- create table usuarios(
--     id_usuario      int             not null,
--     nombre1         varchar(20),
--     nombre2         varchar(20),
--     Primer_ape      varchar(30),
--     Segund_ape      varchar(30),
--     apodo           varchar(60),
--     --informacion---------------
--     Num_contacto    varchar(30),
--     puesto          enum('Jefe De Laboratorio', 'Administrador', 'Laboratorista 1', 'Laboratorista 2'),
--     Curp            varchar(18), -- 4 letras, 6 numeros, 1 letra, 2 letras, 3 letras, 1 num o letra, 1 numero
--     rfc             varchar(13), -- 4 0 3 letras, 6 numeros, 3 num o letras
--     --direccion-----------------
--     calleP          varchar(20),
--     Entrecalles     varchar(50),
--     numero          varchar(10),
--     colonia         varchar(20),
--     cod_postal      varchar(10),
--     --ralaciones ETC------------
--     FOREIGN key(id_usuario) REFERENCES Log_usuarios(id_usuario)
-- );
--======================================--
-- create table clientes(
--     id_clientes     int             primary key     not null    AUTO_INCREMENT,
--     titulo          varchar(60),
--     nom_empr        varchar(60),
--     rfc             varchar(13), -- 4 0 3 letras, 6 numeros, 3 num o letras
--     direc           varchar(100),
--     cod_pos         varchar(10),
--     colonia         varchar(20),
--     ciudad          varchar(30),
--     nombre_contac   varchar(100),
--     numero_contac   varchar(30),
--     email           varchar(50)     unique,
--     nota            text,
--     img             varchar(100),
--     fecha_reg       date
-- );
--======================================--

